# Generated by Django 3.1.1 on 2020-09-05 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='participant',
            table='participant',
        ),
    ]
